on:
  workflow_dispatch:

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Succeed
      run: exit 0
    - name: Print message
      run: echo Success!

   
